Vagrant.configure("2") do |config|
  config.vm.define "lb1" do |lb1|
    lb1.vm.box = "ubuntu/trusty64"
    lb1.vm.network "private_network", ip: "10.0.0.10"
    lb1.vm.provision "shell", path: "https://gist.githubusercontent.com/abraunton/263a1796578ebc487af8/raw/7da0dced1083610bf3275a9fae3dca05bf0ae51a/provision-lb.sh"
  end

  config.vm.define "web1" do |web1|
    web1.vm.box = "williamyeh/ubuntu-trusty64-docker"
    web1.vm.network "private_network", ip: "10.0.0.11"
    web1.vm.provision :shell do |shell|
      shell.args = "1"
      shell.path = "https://gist.githubusercontent.com/ejaycoleman/112e1d10c896213d110216bc112ab88a/raw/a0a43c38177c10fc2c1407bb0ff53b9a47e59ef4/provision-web.sh"
    end
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "williamyeh/ubuntu-trusty64-docker"
    web2.vm.network "private_network", ip: "10.0.0.12"
    web2.vm.provision :shell do |shell|
      shell.args = "2"
      shell.path = "https://gist.githubusercontent.com/ejaycoleman/112e1d10c896213d110216bc112ab88a/raw/a0a43c38177c10fc2c1407bb0ff53b9a47e59ef4/provision-web.sh"
    end
  end
end